import { cpSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, "..");
const crateName = "gaubee-2fa-mobile-bridge";
const libName = "libgaubee_2fa_mobile_bridge.a";
const iosOutputDir = resolve(repoRoot, "mobile", "ios", "Rust");
const generatedDir = resolve(repoRoot, "mobile", "ios", "Core", "Generated");
const headerFile = resolve(generatedDir, "gaubee_2fa_mobile_bridgeFFI.h");
const moduleMapFile = resolve(generatedDir, "gaubee_2fa_mobile_bridgeFFI.modulemap");
const deviceTarget = "aarch64-apple-ios";
const simulatorTargets = ["aarch64-apple-ios-sim", "x86_64-apple-ios"] as const;

function run(command: string, args: string[]): string {
  const output = execFileSync(command, args, {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: "pipe",
  });
  return output.trim();
}

function runInherited(command: string, args: string[]): void {
  execFileSync(command, args, {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

function ensureCommand(command: string, helpText: string): void {
  try {
    run("which", [command]);
  } catch {
    throw new Error(helpText);
  }
}

function ensureUsableXcodeBuild(): void {
  try {
    run("xcodebuild", ["-version"]);
  } catch {
    throw new Error("未检测到可用的完整 Xcode。先安装 Xcode，并执行 sudo xcode-select -s /Applications/Xcode.app");
  }
}

function ensureRustTargets(): void {
  const installed = new Set(run("rustup", ["target", "list", "--installed"]).split(/\s+/).filter(Boolean));
  const requiredTargets = [deviceTarget, ...simulatorTargets];
  const missing = requiredTargets.filter((target) => !installed.has(target));

  if (missing.length > 0) {
    throw new Error(`缺少 Rust iOS targets: ${missing.join(", ")}。先运行 rustup target add ${missing.join(" ")}`);
  }
}

function ensureGeneratedHeaders(): void {
  if (!existsSync(headerFile) || !existsSync(moduleMapFile)) {
    throw new Error("未找到 UniFFI 生成的 iOS headers。先运行 pnpm mobile:bindings。");
  }
}

function prepareHeadersDir(tempRoot: string): string {
  const headersDir = resolve(tempRoot, "headers");
  mkdirSync(headersDir, { recursive: true });
  cpSync(headerFile, resolve(headersDir, "gaubee_2fa_mobile_bridgeFFI.h"));
  cpSync(moduleMapFile, resolve(headersDir, "module.modulemap"));
  return headersDir;
}

function buildStaticLibrary(target: string): string {
  runInherited("cargo", ["build", "-p", crateName, "--target", target, "--release"]);
  const libraryPath = resolve(repoRoot, "target", target, "release", libName);
  if (!existsSync(libraryPath)) {
    throw new Error(`未找到静态库: ${libraryPath}`);
  }
  return libraryPath;
}

function main(): void {
  ensureCommand("lipo", "未找到 lipo。需要安装 Xcode Command Line Tools。\n运行: xcode-select --install");
  ensureCommand("xcodebuild", "未找到 xcodebuild。需要安装完整 Xcode，并执行 sudo xcode-select -s /Applications/Xcode.app");
  ensureUsableXcodeBuild();
  ensureRustTargets();
  runInherited("pnpm", ["mobile:bindings"]);
  ensureGeneratedHeaders();

  const tempRoot = mkdtempSync(resolve(tmpdir(), "gaubee-2fa-ios-rust-"));
  const headersDir = prepareHeadersDir(tempRoot);

  const deviceLib = buildStaticLibrary(deviceTarget);
  const simulatorLibs = simulatorTargets.map(buildStaticLibrary);
  const simulatorUniversalLib = resolve(tempRoot, libName);

  runInherited("lipo", ["-create", ...simulatorLibs, "-output", simulatorUniversalLib]);

  rmSync(iosOutputDir, { recursive: true, force: true });
  mkdirSync(iosOutputDir, { recursive: true });

  runInherited("xcodebuild", [
    "-create-xcframework",
    "-library",
    deviceLib,
    "-headers",
    headersDir,
    "-library",
    simulatorUniversalLib,
    "-headers",
    headersDir,
    "-output",
    resolve(iosOutputDir, "gaubee_2fa_mobile_bridge.xcframework"),
  ]);

  writeFileSync(
    resolve(iosOutputDir, "README.txt"),
    [
      "Generated by pnpm mobile:ios:rust",
      "",
      "This folder is intentionally gitignored.",
      "Rebuild after changing crates/mobile-bridge or mobile/ios/Core/Generated.",
    ].join("\n"),
    "utf8",
  );

  rmSync(tempRoot, { recursive: true, force: true });
  console.log(`已生成 iOS XCFramework: ${resolve(iosOutputDir, "gaubee_2fa_mobile_bridge.xcframework")}`);
}

main();
